# Generated by Django 5.2.15 on 2026-06-30 03:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('link_opened', 'Link opened'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedInFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_shown', 'Not shown'), ('reminder_shown', 'Reminder shown'), ('opened', 'Opened LinkedIn'), ('confirmed', 'Confirmed followed'), ('skipped', 'Reminder skipped')], default='not_shown', max_length=16)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_follow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseNextPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning_another_course', models.BooleanField(default=False)),
                ('interested_course', models.CharField(blank=True, max_length=200)),
                ('expected_timing', models.CharField(blank=True, max_length=100)),
                ('goal', models.CharField(blank=True, choices=[('job_change', 'Job change'), ('promotion', 'Promotion'), ('upskilling', 'Upskilling'), ('other', 'Other')], max_length=16)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_plans', to='batches.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='engagement__student_4f2abf_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'batch'), name='uniq_next_plan')],
            },
        ),
    ]
