# Generated by Django 5.2.15 on 2026-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_utilitylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitylink',
            name='thumbnail_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utilitylink',
            name='thumbnail_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
