# Generated by Django 5.2.15 on 2026-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_devicebinding_devicechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicechangerequest',
            name='approval_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicechangerequest',
            name='approver_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='devicechangerequest',
            name='class_context',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devicechangerequest',
            name='during_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicechangerequest',
            name='old_device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
