# Generated by Django 5.2.15 on 2026-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_facultyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuptoken',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
