# Generated by Django 5.2.15 on 2026-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_setuptoken_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpdevice',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
