# Generated by Django 5.2.15 on 2026-07-30 22:25

from django.db import migrations, models


def collapse_duplicate_pending(apps, schema_editor):
    """Fold pre-existing duplicate PENDING requests down to one per (user, device).

    Without this the AddConstraint below fails outright on any deployment where two
    device-change requests already raced — the exact situation the constraint exists to
    prevent. Migrations that only work on a clean database are not migrations.

    Keeps the *earliest* row in each group: that is the one whose notification actually
    reached the approvers, so it is what a Faculty or Tech Support member sees in their
    queue. The later duplicates are redundant — approving any one of them binds the same
    device to the same student.
    """
    DeviceChangeRequest = apps.get_model("accounts", "DeviceChangeRequest")
    seen: set[tuple] = set()
    doomed: list = []
    for pk, user_id, device in (
        DeviceChangeRequest.objects.filter(status="pending")
        .order_by("created_at", "id")
        .values_list("id", "user_id", "new_device_id")
    ):
        key = (user_id, device)
        if key in seen:
            doomed.append(pk)
        else:
            seen.add(key)
    if doomed:
        DeviceChangeRequest.objects.filter(id__in=doomed).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_totpdevice_failed_attempts"),
    ]

    operations = [
        # Reverse is a no-op: RemoveConstraint makes the migration reversible, but deleted
        # duplicates cannot be resurrected — and re-creating them would only restore the
        # inconsistency this cleaned up.
        migrations.RunPython(collapse_duplicate_pending, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="devicechangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "new_device_id"),
                name="uniq_pending_device_change_per_user_device",
            ),
        ),
    ]
