# Generated by Django 5.2.16 on 2026-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_devicechangerequest_uniq_pending_device_change_per_user_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpdevice',
            name='last_used_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
