# Generated by Django 5.2.15 on 2026-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_integrationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsetting',
            name='secret',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
