# Generated by Django 5.2.16 on 2026-07-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_class_days_batch_class_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'batches'},
        ),
    ]
