# Generated by Django 5.2.15 on 2026-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_task_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
