# Generated by Django 5.2.15 on 2026-07-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_task_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Multiple choice (auto-graded)'), ('file', 'File upload (e.g. Excel)'), ('colab', 'Colab / notebook link')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='file_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
