# Generated by Django 5.2.15 on 2026-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_test_instructions_test_kind_test_max_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='resource_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='resource_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='resource_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
