# Generated by Django 5.2.15 on 2026-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_test_resource_content_type_test_resource_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='resource_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
