# Generated by Django 5.2.16 on 2026-07-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_videoprogress_content_vid_student_27fac5_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoprogress',
            options={'verbose_name_plural': 'video progress'},
        ),
    ]
