# Generated by Django 5.2.15 on 2026-06-23 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=30)),
                ('reference_id', models.CharField(max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'student', 'reference_id'), name='uniq_escalation')],
            },
        ),
    ]
