# Generated by Django 5.2.15 on 2026-07-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_class_days_batch_class_end_time_and_more'),
        ('escalations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='escalation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='batches.batch'),
        ),
    ]
