# Generated by Django 5.2.15 on 2026-06-22 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('live', 'Live class'), ('video', 'Video'), ('test', 'Test'), ('task', 'Task')], max_length=10)),
                ('reference_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='batches.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'batch'], name='attendance__student_d339a7_idx'), models.Index(fields=['batch'], name='attendance__batch_i_f95258_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'source', 'reference_id'), name='uniq_attendance_event')],
            },
        ),
    ]
