# Generated by Django 5.2.15 on 2026-06-30 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('not_reachable', 'Not reachable'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='source',
            field=models.CharField(choices=[('login', 'Login'), ('live', 'Live class'), ('video', 'Video'), ('test', 'Test'), ('task', 'Task')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['batch', 'source', 'date'], name='attendance__batch_i_4aa962_idx'),
        ),
        migrations.AddField(
            model_name='absencefollowup',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_followups', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='absencefollowup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencefollowup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='absencefollowup',
            index=models.Index(fields=['batch', 'status'], name='attendance__batch_i_40580b_idx'),
        ),
        migrations.AddConstraint(
            model_name='absencefollowup',
            constraint=models.UniqueConstraint(fields=('student', 'batch'), name='uniq_absence_followup'),
        ),
    ]
