# Generated by Django 5.2.15 on 2026-07-06 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_absencefollowup_attendanceevent_device_id_and_more'),
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['student', 'batch', 'source', 'date'], name='attendance__student_b815b6_idx'),
        ),
    ]
