# Generated by Django 5.2.15 on 2026-07-30 22:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_from_notifications(apps, schema_editor):
    """Seed the log from the ``absence_reminder`` notifications the old dedup read.

    The previous implementation inferred "already reminded" from Notification rows. If the
    new table starts empty, the first run after deploy sees nobody as reminded and re-sends
    to every student who was already contacted earlier the same day. Backfilling the whole
    history (not just today) also keeps the table honest about what it claims to record.
    """
    Notification = apps.get_model("notifications", "Notification")
    AbsenceReminderLog = apps.get_model("attendance", "AbsenceReminderLog")

    pairs = {
        (recipient_id, timezone.localtime(created_at).date())
        for recipient_id, created_at in Notification.objects.filter(
            kind="absence_reminder"
        ).values_list("recipient_id", "created_at")
    }
    if pairs:
        AbsenceReminderLog.objects.bulk_create(
            [AbsenceReminderLog(student_id=student, day=day) for student, day in pairs],
            ignore_conflicts=True,
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendanceevent_attendance__student_b815b6_idx"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["day"], name="attendance__day_257469_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "day"), name="uniq_absence_reminder_per_day"
                    )
                ],
            },
        ),
        # Reverse is a no-op: DeleteModel drops the table on unapply, so there is nothing
        # to undo row-by-row.
        migrations.RunPython(backfill_from_notifications, migrations.RunPython.noop),
    ]
