# Generated by Django 5.2.16 on 2026-07-31 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_absencereminderlog'),
        ('batches', '0004_alter_batch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['student', 'source', 'date'], name='attendance__student_891802_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['date', 'source'], name='attendance__date_823f7b_idx'),
        ),
    ]
