# Generated by Django 5.2.15 on 2026-06-30 03:13

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def backfill_status(apps, schema_editor):
    """Resolved threads -> resolved; threads with replies -> answered; else open."""
    Thread = apps.get_model("forum", "Thread")
    Thread.objects.filter(resolved=True).update(status="resolved")
    answered = (
        Thread.objects.filter(resolved=False)
        .annotate(rc=Count("replies"))
        .filter(rc__gt=0)
        .values_list("id", flat=True)
    )
    Thread.objects.filter(id__in=list(answered)).update(status="answered")


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=10),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['status'], name='forum_threa_status_bc04d3_idx'),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
