# Generated by Django 5.2.16 on 2026-07-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_threadattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'replies'},
        ),
    ]
