# Generated by Django 5.2.15 on 2026-06-30 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('received', 'Received'), ('escalated', 'Escalated')], default='pending', max_length=12)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cert_followup', to='enrollments.enrollment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='certificati_status_5c946c_idx')],
            },
        ),
    ]
