# Generated by Django 5.2.16 on 2026-07-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_certificatefollowup'),
        ('enrollments', '0002_enrollment_address_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='enrollments.enrollment'),
        ),
    ]
