# Generated by Django 5.2.15 on 2026-06-29 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_min', models.PositiveSmallIntegerField()),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='liveclasses.liveclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('live_class', 'offset_min'), name='uniq_live_reminder')],
            },
        ),
    ]
