# Generated by Django 5.2.16 on 2026-07-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0003_liveclass_cancel_reason_liveclass_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['scheduled_at'], 'verbose_name_plural': 'live classes'},
        ),
    ]
